apiVersion: batch/v1
kind: Job
metadata:
  name: model-training
spec:
  template:
    spec:
      containers:
      - name: model-trainer
        image: harshith12/new-train-36
        resources:
          limits:
            nvidia.com/gpu: 1
        volumeMounts:
        - name: model-storage
          mountPath: /mnt
      restartPolicy: Never
      volumes:
      - name: model-storage
        persistentVolumeClaim:
          claimName: my-model-pvc
      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-l4